[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
graph = "0.3.1"
num = "0.4.3"
paste = "1.0.15"
rand = "0.8.5"
regex = "1.11.1"

[lints.clippy]
all = "warn"
pedantic = "warn"
style = "warn"
nursery = "warn"
